spring.datasource.url=jdbc:mariadb://localhost:3306/booking?useSSL=false&serverTimezone=UTC
booking.property=Booking Profile Dev Updated
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true